/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
  RouterHistory,
} from '@stencil/router';


export namespace Components {

  interface EnseignantAdd {
    'home': RouterHistory;
  }
  interface EnseignantAddAttributes extends StencilHTMLAttributes {
    'home'?: RouterHistory;
  }

  interface EnseignantDelete {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface EnseignantDeleteAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface EnseignantDetail {
    'match': MatchResults;
  }
  interface EnseignantDetailAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface EnseignantEdit {
    'match': MatchResults;
    'nom': string;
  }
  interface EnseignantEditAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
    'nom'?: string;
  }

  interface EnseignantSearch {}
  interface EnseignantSearchAttributes extends StencilHTMLAttributes {}

  interface EnseignantSearchname {}
  interface EnseignantSearchnameAttributes extends StencilHTMLAttributes {}

  interface SpiEnseignant {}
  interface SpiEnseignantAttributes extends StencilHTMLAttributes {}

  interface FormationAdd {
    'home': RouterHistory;
  }
  interface FormationAddAttributes extends StencilHTMLAttributes {
    'home'?: RouterHistory;
  }

  interface FormationDelete {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface FormationDeleteAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface FormationDetail {
    'match': MatchResults;
  }
  interface FormationDetailAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface FormationEdit {
    'match': MatchResults;
    'nomFormation': string;
  }
  interface FormationEditAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
    'nomFormation'?: string;
  }

  interface FormationSearchname {}
  interface FormationSearchnameAttributes extends StencilHTMLAttributes {}

  interface SpiFormation {}
  interface SpiFormationAttributes extends StencilHTMLAttributes {}

  interface SpiHeader {}
  interface SpiHeaderAttributes extends StencilHTMLAttributes {}

  interface SpiHome {}
  interface SpiHomeAttributes extends StencilHTMLAttributes {}

  interface SpiRoot {}
  interface SpiRootAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'EnseignantAdd': Components.EnseignantAdd;
    'EnseignantDelete': Components.EnseignantDelete;
    'EnseignantDetail': Components.EnseignantDetail;
    'EnseignantEdit': Components.EnseignantEdit;
    'EnseignantSearch': Components.EnseignantSearch;
    'EnseignantSearchname': Components.EnseignantSearchname;
    'SpiEnseignant': Components.SpiEnseignant;
    'FormationAdd': Components.FormationAdd;
    'FormationDelete': Components.FormationDelete;
    'FormationDetail': Components.FormationDetail;
    'FormationEdit': Components.FormationEdit;
    'FormationSearchname': Components.FormationSearchname;
    'SpiFormation': Components.SpiFormation;
    'SpiHeader': Components.SpiHeader;
    'SpiHome': Components.SpiHome;
    'SpiRoot': Components.SpiRoot;
  }

  interface StencilIntrinsicElements {
    'enseignant-add': Components.EnseignantAddAttributes;
    'enseignant-delete': Components.EnseignantDeleteAttributes;
    'enseignant-detail': Components.EnseignantDetailAttributes;
    'enseignant-edit': Components.EnseignantEditAttributes;
    'enseignant-search': Components.EnseignantSearchAttributes;
    'enseignant-searchname': Components.EnseignantSearchnameAttributes;
    'spi-enseignant': Components.SpiEnseignantAttributes;
    'formation-add': Components.FormationAddAttributes;
    'formation-delete': Components.FormationDeleteAttributes;
    'formation-detail': Components.FormationDetailAttributes;
    'formation-edit': Components.FormationEditAttributes;
    'formation-searchname': Components.FormationSearchnameAttributes;
    'spi-formation': Components.SpiFormationAttributes;
    'spi-header': Components.SpiHeaderAttributes;
    'spi-home': Components.SpiHomeAttributes;
    'spi-root': Components.SpiRootAttributes;
  }


  interface HTMLEnseignantAddElement extends Components.EnseignantAdd, HTMLStencilElement {}
  var HTMLEnseignantAddElement: {
    prototype: HTMLEnseignantAddElement;
    new (): HTMLEnseignantAddElement;
  };

  interface HTMLEnseignantDeleteElement extends Components.EnseignantDelete, HTMLStencilElement {}
  var HTMLEnseignantDeleteElement: {
    prototype: HTMLEnseignantDeleteElement;
    new (): HTMLEnseignantDeleteElement;
  };

  interface HTMLEnseignantDetailElement extends Components.EnseignantDetail, HTMLStencilElement {}
  var HTMLEnseignantDetailElement: {
    prototype: HTMLEnseignantDetailElement;
    new (): HTMLEnseignantDetailElement;
  };

  interface HTMLEnseignantEditElement extends Components.EnseignantEdit, HTMLStencilElement {}
  var HTMLEnseignantEditElement: {
    prototype: HTMLEnseignantEditElement;
    new (): HTMLEnseignantEditElement;
  };

  interface HTMLEnseignantSearchElement extends Components.EnseignantSearch, HTMLStencilElement {}
  var HTMLEnseignantSearchElement: {
    prototype: HTMLEnseignantSearchElement;
    new (): HTMLEnseignantSearchElement;
  };

  interface HTMLEnseignantSearchnameElement extends Components.EnseignantSearchname, HTMLStencilElement {}
  var HTMLEnseignantSearchnameElement: {
    prototype: HTMLEnseignantSearchnameElement;
    new (): HTMLEnseignantSearchnameElement;
  };

  interface HTMLSpiEnseignantElement extends Components.SpiEnseignant, HTMLStencilElement {}
  var HTMLSpiEnseignantElement: {
    prototype: HTMLSpiEnseignantElement;
    new (): HTMLSpiEnseignantElement;
  };

  interface HTMLFormationAddElement extends Components.FormationAdd, HTMLStencilElement {}
  var HTMLFormationAddElement: {
    prototype: HTMLFormationAddElement;
    new (): HTMLFormationAddElement;
  };

  interface HTMLFormationDeleteElement extends Components.FormationDelete, HTMLStencilElement {}
  var HTMLFormationDeleteElement: {
    prototype: HTMLFormationDeleteElement;
    new (): HTMLFormationDeleteElement;
  };

  interface HTMLFormationDetailElement extends Components.FormationDetail, HTMLStencilElement {}
  var HTMLFormationDetailElement: {
    prototype: HTMLFormationDetailElement;
    new (): HTMLFormationDetailElement;
  };

  interface HTMLFormationEditElement extends Components.FormationEdit, HTMLStencilElement {}
  var HTMLFormationEditElement: {
    prototype: HTMLFormationEditElement;
    new (): HTMLFormationEditElement;
  };

  interface HTMLFormationSearchnameElement extends Components.FormationSearchname, HTMLStencilElement {}
  var HTMLFormationSearchnameElement: {
    prototype: HTMLFormationSearchnameElement;
    new (): HTMLFormationSearchnameElement;
  };

  interface HTMLSpiFormationElement extends Components.SpiFormation, HTMLStencilElement {}
  var HTMLSpiFormationElement: {
    prototype: HTMLSpiFormationElement;
    new (): HTMLSpiFormationElement;
  };

  interface HTMLSpiHeaderElement extends Components.SpiHeader, HTMLStencilElement {}
  var HTMLSpiHeaderElement: {
    prototype: HTMLSpiHeaderElement;
    new (): HTMLSpiHeaderElement;
  };

  interface HTMLSpiHomeElement extends Components.SpiHome, HTMLStencilElement {}
  var HTMLSpiHomeElement: {
    prototype: HTMLSpiHomeElement;
    new (): HTMLSpiHomeElement;
  };

  interface HTMLSpiRootElement extends Components.SpiRoot, HTMLStencilElement {}
  var HTMLSpiRootElement: {
    prototype: HTMLSpiRootElement;
    new (): HTMLSpiRootElement;
  };

  interface HTMLElementTagNameMap {
    'enseignant-add': HTMLEnseignantAddElement
    'enseignant-delete': HTMLEnseignantDeleteElement
    'enseignant-detail': HTMLEnseignantDetailElement
    'enseignant-edit': HTMLEnseignantEditElement
    'enseignant-search': HTMLEnseignantSearchElement
    'enseignant-searchname': HTMLEnseignantSearchnameElement
    'spi-enseignant': HTMLSpiEnseignantElement
    'formation-add': HTMLFormationAddElement
    'formation-delete': HTMLFormationDeleteElement
    'formation-detail': HTMLFormationDetailElement
    'formation-edit': HTMLFormationEditElement
    'formation-searchname': HTMLFormationSearchnameElement
    'spi-formation': HTMLSpiFormationElement
    'spi-header': HTMLSpiHeaderElement
    'spi-home': HTMLSpiHomeElement
    'spi-root': HTMLSpiRootElement
  }

  interface ElementTagNameMap {
    'enseignant-add': HTMLEnseignantAddElement;
    'enseignant-delete': HTMLEnseignantDeleteElement;
    'enseignant-detail': HTMLEnseignantDetailElement;
    'enseignant-edit': HTMLEnseignantEditElement;
    'enseignant-search': HTMLEnseignantSearchElement;
    'enseignant-searchname': HTMLEnseignantSearchnameElement;
    'spi-enseignant': HTMLSpiEnseignantElement;
    'formation-add': HTMLFormationAddElement;
    'formation-delete': HTMLFormationDeleteElement;
    'formation-detail': HTMLFormationDetailElement;
    'formation-edit': HTMLFormationEditElement;
    'formation-searchname': HTMLFormationSearchnameElement;
    'spi-formation': HTMLSpiFormationElement;
    'spi-header': HTMLSpiHeaderElement;
    'spi-home': HTMLSpiHomeElement;
    'spi-root': HTMLSpiRootElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
